### ISSUE TITLE
Runloop discussion

### ISSUE THREAD

**Issue by rwols** [Wramberg/TerminalView#11]
So right now the plugin is centered around this idea of constantly polling for data. This works, but it drains CPU even if sublime is in the background. It may be a better (greener?) alternative to have a thread reading from the `_pty` file descriptor. I'm not an expert in pty's, but it is perhaps possible to just read from it and block until some new data arrives. This blocking is then not a problem if it's done in a separate thread. As soon as new data arrives, just have your callback functions update the screen and so forth (also for key-callbacks). The only problem with this scheme is perhaps updating the width and height of the terminal view when the user resizes the window; maybe that can have its own thread that just polls every second or so.

**Comment by Wramberg** [comment]
Some good points. I'd like to note that in my setup the terminal uses very little CPU on idle. Regardless this would be a nice optimization.

Right now we are actually using select in LinuxPty.py with a timeout of 0. That could be changed to inf. and resize/close checks could be moved to a separate thread.

I might also be interested in splitting shell polling and view updates into separate threads simply from a performance point of view. but that requires some more consideration.

Overall I think this would be a nice thing to play around with but right now I'm trying to find the shortest path to a stable, mature'ish plugin so I can add it to package control (in other words it might be a while before I atleast get the time to look into it).

**Comment by Wramberg** [comment]
After 42a1cf48ee97893e2a0171c36d8bb5a9bd7ef736 we are now using the timeout as mentioned. It is a relatively low timeout however in order for the runloop to service scroll, resize checks, etc.

The main CPU usage is calling a ST3 text command 30 times per second right now as required by the sublime buffer update logic. I think this could be optimized a bit as well so I'll have a look into that soon.

**Comment by Wramberg** [comment]
42a1cf48ee97893e2a0171c36d8bb5a9bd7ef736 did in some cases cause view updates too fast so it was partially reverted. The more important discovery that ST3 command calls was the main contributor has now been accounted for in 153d0aa0ee72daaf1a0a7733b31de64296d99aca. 

It seems an idle terminal view uses incredibly little CPU now.

**Comment by rwols** [comment]
I just pulled the latest devel branch and it seems to work fine!

**Comment by rwols** [comment]
I think you should make the thread take a weakref.ref to the method though, and join it in the `__del__` of the TerminalView class (sorry for hammering on this!)

**Comment by Wramberg** [comment]
Hehe thats alright - but I fail to see which advantage that would bring. As long as the thread is running I want the class to be present - but when the thread stops it will release it's reference and everything is good.

**Comment by Wramberg** [comment]
Think I'll close this one at least for now - the run loop is pretty optimized imo and my time is probably gonna be going into gateone testing. The weakref stuff we can discuss in https://github.com/Wramberg/TerminalView/pull/40 if need ;-)

**Comment by rwols** [comment]
Yeah, I'm pretty happy with the performance to be honest. Nice job!
