### ISSUE TITLE
Change Log as Package Control messages

### ISSUE THREAD

**Issue by nchursin** [Wramberg/TerminalView#16]
It'd be really nice to get info on all the latest changes to the plugin with [Package Control messaging system](https://packagecontrol.io/docs/messaging).

**Comment by Wramberg** [comment]
I agree and I actually just started looking to this (but Im unfamiliar with it). Do you know if its possible to point all upgrades to the same file ? or do I have to basically split the changelog into separate files ? See example below

```
{
	"install": "messages/install.txt",
	"*": "messages/changelog.txt",
}
```

**Comment by Wramberg** [comment]
56054d89a942300de7943c9a16ed5ecf6d67f0c3 includes the messages for current versions and install.

**Comment by nchursin** [comment]
I think there might be a problem if someone updates the package from for example 2 versions below (e.g. 0.1.0 to 0.1.2). In this case, package control shows both messages for v0.1.1 and v0.1.2.
And if both versions have change log in the same file, it will be displayed twice.
But I'm not sure how it works with `*`, never used it myself.

**Comment by Wramberg** [comment]
Yeah you are probably right - for now I have gone for the "standard" approach :-)
