### ISSUE TITLE
Regression in 0.4.0

### ISSUE THREAD

**Issue by aziz** [Wramberg/TerminalView#17]
Everything was working just fine before but now my prompt has some unwanted output
<img width="599" alt="screen shot 2017-07-01 at 2 46 06 am" src="https://user-images.githubusercontent.com/3202/27757858-aac996ba-5e07-11e7-8d35-63bd0a0b9847.png">

**Comment by Wramberg** [comment]
That seems odd - 0.4.0 does not really change anything regarding the shell or the parsing of its output. Please provide some information on how to reproduce this like

* What arguments do you call the terminalview_open command with.
* What is the output of env
* etc.

**Comment by aziz** [comment]
command: terminal_view_open {"cmd": "/bin/bash -l", "title": "Terminal (bash)"}
bash: 4.4.12
ST3: 3140

I have variables in env which contain color escape codes

**Comment by Wramberg** [comment]
Are you on linux or macOS ?
I would like to see a dump of `env` so I can reproduce your setup.
What happens if you run bash with the `-l` option like
```
terminal_view_open {"cmd": "/bin/bash", "title": "Terminal (bash)"}
```
If we can narrow down whats causing the issue I can include it in the tests to avoid it in the future.

**Comment by aziz** [comment]
> Are you on linux or macOS ?
macOS

**Comment by aziz** [comment]
I've tried these combinations
```
  { "caption": "Custom Terminal", "command": "terminal_view_open", "args": {
    "cmd": "/bin/bash", "title": "Terminal (bash)"}
  },
  { "caption": "Custom Terminal 2", "command": "terminal_view_open", "args": {
    "cmd": "/usr/local/bin/bash", "title": "Terminal (bash)"}
  },
```

They all result in the same issue. 
BTW, I have two bash versions. one which comes bundled with macOS `/bin/bash`
and the other which is newer (GNU bash 4.4.12) installed using homebrew in `/usr/local/bin/bash`

I'll publish my env output in a gist

**Comment by aziz** [comment]
https://gist.github.com/aziz/438fa0099ad6c71999777dc5d091e3ba

**Comment by Wramberg** [comment]
Unfortunately I don't have any way of testing on macOS. Regardless I see your env contains

```
TERM=xterm-256color
```

which will not work with the internal terminal emulator, pyte, since it's a VTxxx emulator (not xterm). The plugin sets the TERM variable to linux: https://github.com/Wramberg/TerminalView/blob/master/linux_pty.py#L25

My guess is you have some bash_profile or similar configured to change the TERM variable. Maybe you can try commenting that out. If I change the TERM variable I get the same kind of "garbage" since pyte cannot parse the data it receives from the shell.

**Comment by Wramberg** [comment]
Any updates on this @aziz ? Ive been looking into an xterm terminal emulator for python but until this has been implemented the plugin is not going to support xterm behavior

**Comment by aziz** [comment]
I've tested this on my other computer with the exact same bashrc and bash_profile. On my other computer everything works just fine. So I don't know what's causing this issue and I need to investigate further. My guess is that [iTerm2 Shell Integration feature](https://www.iterm2.com/documentation-shell-integration.html) might cause this but it needs to be verified.

I think you should close this issue and move on, I'll open another issue if I found the real source of the issue.

**Comment by Wramberg** [comment]
Alright thanks for the feedback - I think this plugin is getting to a point where it's used in many different setups which is hard to test so feel free to give an update if you find out more.
