### ISSUE TITLE
Lines with red boarders and no text coloring

### ISSUE THREAD

**Issue by Corleo** [Wramberg/TerminalView#18]
Hello, Jesper.

I really liked your sublime terminal, it is great and runs smoothly in my computer, but it is not working like it was shown in the docs. In my machine it is displaying red boarders around text lines and the expected prompt coloring didn't work. I'm running sublime text 3 with Ubuntu 14.04.5 LTS x64 and with TerminalView default configs. 

![red_boarders](https://user-images.githubusercontent.com/9902249/27774106-05e1f0ec-5f61-11e7-8bba-d5ba4ff3b027.png)

Do you know if this is about some sublime config/package conflict?

**Comment by Wramberg** [comment]
Without more info my best guess is some kind of incompliance between your setup and pyte, the internal terminal emulator.

Could your provide the following info ?

* OS used
* ST3 version
* Bash version
* Arguments being used with the terminal_view_open command
* If possible, a dump of the environment vars from the terminal view (call `env` in the terminal inside ST3)

**Comment by AlanCristhian** [comment]
I have the same problem:

- Ubuntu 16.04 LTS x64
- ST3, Build 3126
- GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

**Comment by Wramberg** [comment]
Could one of you dump the output of `env` when called inside the terminal in ST3 ? I need it to replicate your setup.

**Comment by AlanCristhian** [comment]
XDG_VTNR=7
XDG_SESSION_ID=c2
CLUTTER_IM_MODULE=xim
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/alancristhian
GIO_LAUNCHED_DESKTOP_FILE_PID=3927
SESSION=ubuntu
GPG_AGENT_INFO=/home/alancristhian/.gnupg/S.gpg-agent:0:1
TERM=linux
XDG_MENU_PREFIX=gnome-
SHELL=/bin/bash
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1884
GNOME_KEYRING_CONTROL=
GTK_MODULES=gail:atk-bridge:unity-gtk-module
USER=alancristhian
QT_ACCESSIBILITY=1
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
SESSION_MANAGER=local/ubuntu:@/tmp/.ICE-unix/2076,unix/ubuntu:/tmp/.ICE-unix/2076
GIO_LAUNCHED_DESKTOP_FILE=/home/alancristhian/.local/share/applications/sublime_text.desktop
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
DESKTOP_SESSION=ubuntu
PATH=/home/alancristhian/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/alancristhian/bin
QT_QPA_PLATFORMTHEME=appmenu-qt5
QT_IM_MODULE=ibus
JOB=unity-settings-daemon
XDG_SESSION_TYPE=x11
PWD=/home/alancristhian/andres-3/cgi-bin/forgiven
XMODIFIERS=@im=ibus
LANG=es_AR.UTF-8
GNOME_KEYRING_PID=
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
GDM_LANG=es_AR
COMPIZ_CONFIG_PROFILE=ubuntu
IM_CONFIG_PHASE=1
GDMSESSION=ubuntu
GTK2_MODULES=overlay-scrollbar
SESSIONTYPE=gnome-session
HOME=/home/alancristhian
SHLVL=1
XDG_SEAT=seat0
LANGUAGE=es_AR:es
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
UPSTART_INSTANCE=
UPSTART_EVENTS=xsession started
XDG_SESSION_DESKTOP=ubuntu
LOGNAME=alancristhian
COMPIZ_BIN_PATH=/usr/bin/
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-FHBIe5KFg5
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
QT4_IM_MODULE=xim
INSTANCE=
UPSTART_JOB=unity7
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
XDG_CURRENT_DESKTOP=Unity
GTK_IM_MODULE=ibus
XAUTHORITY=/home/alancristhian/.Xauthority
_=/usr/bin/env

**Comment by Wramberg** [comment]
Thanks @AlanCristhian Ill look into it when I get the chance. Until then I guess you could fix it by disabling colors in the settings.

**Comment by Corleo** [comment]
Yes, here it is:

* OS used: 14.04.5 LTS x64
* ST3 version: build 3126
* Bash version: 4.3.11(1)-release (x86_64-pc-linux-gnu)
* Arguments being used with the terminal_view_open command: I'm oppening the terminal_view using ctrl+shift+p -> "Open Terminal View - Bash"
* Dump of the environment vars from the ST3 terminal view: 
PWD=/home/corleo                                                                                                                                              
JAVA_HOME=/usr/lib/jvm/java-8-oracle                                                                                                                          
XMODIFIERS=@im=ibus                                                                                                                                           
LANG=pt_BR.UTF-8                                                                                                                                              
GNOME_KEYRING_PID=2360                                                                                                                                        
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path                                                                                                         
GDM_LANG=pt_BR                                                                                                                                                
LC_MEASUREMENT=pt_BR.UTF-8                                                                                                                                    
NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript                                                                                         
COMPIZ_CONFIG_PROFILE=ubuntu                                                                                                                                  
IM_CONFIG_PHASE=1                                                                                                                                             
GDMSESSION=ubuntu                                                                                                                                             
SESSIONTYPE=gnome-session                                                                                                                                     
XDG_SEAT=seat0                                                                                                                                                
HOME=/home/corleo                                                                                                                                             
SHLVL=1                                                                                                                                                       
LANGUAGE=pt_BR:pt:pt_PT:en                                                                                                                                    
GNOME_DESKTOP_SESSION_ID=this-is-deprecated                                                                                                                   
UPSTART_INSTANCE=                                                                                                                                             
LOGNAME=corleo                                                                                                                                                
UPSTART_EVENTS=started starting                                                                                                                               
QT4_IM_MODULE=xim                                                                                                                                             
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-bumOTLr05Z                                                                                                   
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/                                                                                
J2SDKDIR=/usr/lib/jvm/java-8-oracle                                                                                                                           
LESSOPEN=| /usr/bin/lesspipe %s                                                                                                                               
INSTANCE=Unity                                                                                                                                                
TEXTDOMAIN=im-config                                                                                                                                          
UPSTART_JOB=unity-settings-daemon                                                                                                                             
DISPLAY=:0                                                                                                                                                    
XDG_RUNTIME_DIR=/run/user/1000                                                                                                                                
XDG_CURRENT_DESKTOP=Unity                                                                                                                                     
GTK_IM_MODULE=ibus                                                                                                                                            
J2REDIR=/usr/lib/jvm/java-8-oracle/jre                                                                                                                        
LESSCLOSE=/usr/bin/lesspipe %s %s                                                                                                                             
LC_TIME=pt_BR.UTF-8                                                                                                                                           
TEXTDOMAINDIR=/usr/share/locale/                                                                                                                              
XAUTHORITY=/home/corleo/.Xauthority                                                                                                                           
LC_NAME=pt_BR.UTF-8                                                                                                                                           
_=/usr/bin/env

**Comment by Wramberg** [comment]
I haven't been able to reproduce this so far.

* I assume the red lines go away when you turn off dynamic colors ?
* Maybe it is related to another plugin or perhaps some global setting. Could you maybe try a clean install (if it isn't too much trouble) ?
* Could also be related to some thirdparty stuff like iterm or something as seen in #17 

I hope we can figure it out and hopefully avoid any issues in the future

**Comment by Corleo** [comment]
No, the red lines don't go away when I turn off colors in the terminalview settings. Nothing changes.
What I noticed was that the output of the terminalview for `$ env`, for example, adds some weird white spaces and line brakes that are seen when I copy and paste then to a text file:

![printscreen](https://user-images.githubusercontent.com/9902249/27898362-0c3c8fb8-61fc-11e7-9119-73d330a92661.png)


and I have not tried a fresh install yet. I'll try tomorrow.

can you try a fresh install too but with my settings for ../Packages/User dir?
https://github.com/Corleo/st_settings.git

**Comment by Wramberg** [comment]
Ill see if I can get the time later today to try your settings.

If disabling terminal view colors does not work it seems very likely that its a plugin conflict or ST3 configuration issue that I haven't thought of.

**Comment by Corleo** [comment]
Hi, @Wramberg  

With a ST3 fresh install with only package control and terminalview the red lines didn't appear, but my prompt colors didn't appear either. It wasn't supposed that the coloring should be get from bash terminal by default?

![print_terminalview](https://user-images.githubusercontent.com/9902249/27925919-dd5f7fc8-625c-11e7-87bd-7fcbe2087a1c.png)

Then, after installing my ST3 settings with my plugins the red lines came back. :)

**Comment by Wramberg** [comment]
#### In regards to colors
Im afraid the internal terminal emulator doesnt parse the colors of your prompt (only supports 8 colors or something). Im looking into a new terminal emulator which supports xterm and a lot more colors but its still in development.

#### In regards to red highlights
Had a look at your packages and I think its caused by trailing space highlighting. The default blank char for the internal terminal emulator is a space. I might be able to change that and remove trailing white space. Ill look into that.  Until then the only workaround is to disable that I guess.

**Comment by Corleo** [comment]
@Wramberg, you were right. 

It was an issue with the TrailingSpaces highlight and disabling the plugin removes the red lines.

Thanks!!

**Comment by adexerivera** [comment]
@Wramberg, you are right,

but I would like to have activated the TrailingSpaces plugin too.

Thanks!!
