### ISSUE TITLE
Settings enhancements

### ISSUE THREAD

**Issue by nchursin** [Wramberg/TerminalView#20]
I have a couple of suggestions about settings commands.
1. Create Command Pallete commands - I usually don't use the settings menu, and I'm pretty sure I'm not the only one. With command palette, you don't have to leave your keyboard.
2. Use `edit_settings` instead of `open_file` - it opens both default and user's settings in a split view. It makes editing settings much easier.

**Comment by Wramberg** [comment]
Good ideas - Ill look into this when possible :)

**Comment by Wramberg** [comment]
You are right the edit_settings really makes everything a lot easier
