### ISSUE TITLE
Port to Cud

### ISSUE THREAD

**Issue by Alexey-T** [Wramberg/TerminalView#21]
I want to port this plugin to CudaText: but need help for this.
maybe you can refactor code, so that some part will be, which I can use?
Tks.

**Comment by Wramberg** [comment]
I do have a refactor planned since I am looking into a new internal terminal emulator that supports xterm. What do you have in mind ? Abstracting ST3 API calls away behind a single module or ?

**Comment by Alexey-T** [comment]
Moving all ST3 calls to a new module, and Term emulation module should be w/o ST3 calls. my Cud plugin will use this part w/o ST3.

**Comment by Wramberg** [comment]
Im just gonna close this. I trust you can refactor yourself if still relevant - I just don't have the time to support something like this.
