### ISSUE TITLE
support bracketed paste mode

### ISSUE THREAD

**Issue by randy3k** [Wramberg/TerminalView#22]
Pasting the clipboard content to terminal is not working. It just doesn't do anything. It would be nice to also support bracketed paste mode if you are working on it.

The tmux emulator  [pymux](https://github.com/jonathanslenders/pymux/blob/9569dda0c74c5e8b1dd8563d7ecef2c184410db7/pymux/screen.py#L126) which also uses `pyte` may be a good starting point to support it.

<details>

* OS used: Mac OS 10.12.5 
* ST3 version version: 3126 osx x64 channel: stable
* Bash version 3.2.57(1)-release  and 4.4.12(1)-release
* Arguments being used with the terminal_view_open command

```
    {
      "caption": "Open Terminal View - Bash 4",
      "command": "terminal_view_open",
      "args"   : {"title": "Terminal (zsh)", "cmd": "/usr/local/bin/bash -l"},
    }
```

**Comment by Wramberg** [comment]
Nothing happening on paste is very unexpected - all the paste does at the moment is "emulate" keypresses.

```
class TerminalViewPaste(sublime_plugin.TextCommand):
    def run(self, edit):
        if not self.view.terminal_view_keypress_callback:
            return

        keypress_cb = self.view.terminal_view_keypress_callback
        copied = sublime.get_clipboard()
        copied = copied.replace("\r\n", "\n")
        for char in copied:
            if char == "\n" or char == "\r":
                keypress_cb("enter")
            elif char == "\t":
                keypress_cb("tab")
            else:
                keypress_cb(char)
```

when you hit a key manually its the same keypress_cb that gets called. Are you copying a simple string or ?

**Comment by randy3k** [comment]
I see. `ctrl+shift+v` works, but MacOS actually uses `super+v`

**Comment by randy3k** [comment]
Defining 
```
    {"keys": ["super+v"], "command": "terminal_view_paste", "context": [{"key": "setting.terminal_view"}]},
```
now works for me.

Let's keep this issue for the bracketed paste mode.

**Comment by Wramberg** [comment]
Great - haven't thought about the alternative keybindings in macOS. Maybe I should make a macOS specific default keymap.

**Comment by Wramberg** [comment]
Hey @randy3k. 8992cbd5010d19590bdae77b095162787c4e1739 should include support for bracketed paste mode. You can enable it from the shell by printing the typical \e[?2004h or by simply setting the bracketed flag when calling terminal_view_paste.

I tried downloading and building bash 4.4 but I think it statically linked with my readline 6 lib (need readline 7 for it to work). Instead of manually downloading, building etc. again for both I figured you could test it maybe ?

**Comment by randy3k** [comment]
It looks like it is working great with ipython. Consider this piece of code

```
class foo():
    def bar():
        pass



    def bla():
        pass
```

before
<img width="481" alt="screen shot 2017-07-30 at 5 45 11 pm" src="https://user-images.githubusercontent.com/1690993/28757343-ddeb0822-754e-11e7-9059-8186a997eb65.png">

!!! missing the second piece!

after
<img width="457" alt="screen shot 2017-07-30 at 5 46 10 pm" src="https://user-images.githubusercontent.com/1690993/28757348-fe32b06c-754e-11e7-835d-220c966d0ecf.png">

**Comment by Wramberg** [comment]
Great! Thanks for testing it.
