### ISSUE TITLE
restore cursor position when pressing <esc>

### ISSUE THREAD

**Issue by randy3k** [Wramberg/TerminalView#23]
It would be nice if `<esc>` will restore the cursor to the original prompt location when the cursor has been moved to other location, for example after copying something or just after an accidental click.

By the way, excellent work. I have been waiting a prefer emulator for ages.

**Comment by Wramberg** [comment]
Escape is forwarded to the shell as its a valid key used by e.g. vim. I'm not against making it possible to reset the cursor but lets find a key thats not used by the shell :-)

**Comment by randy3k** [comment]
it is only enabled when the cursor has moved, it will not affect any other usage of esc.

**Comment by Wramberg** [comment]
Ah ok - well in that case I guess `esc` would make sense 👍

**Comment by Wramberg** [comment]
@randy3k could you double-check `devel` to see if it behaves at expected after merging #31 (escape resets cursor position when its moved but is sent to shell when cursor is in the right place) before we close this issues ?

**Comment by randy3k** [comment]
It is working. If the cursor has not been moved, `<esc>-<delete>` will default the previous word.

**Comment by Wramberg** [comment]
Great :+1:
