### ISSUE TITLE
send `SIGWINCH` upon terminal resize

### ISSUE THREAD

**Issue by randy3k** [Wramberg/TerminalView#25]
`SIGWINCH` needs to be sent after the terminal has resized.

<img width="1081" alt="screen shot 2017-07-12 at 3 22 13 am" src="https://user-images.githubusercontent.com/1690993/28106282-53a3c75e-66b1-11e7-98eb-d1bc47d60743.png">

**Comment by randy3k** [comment]
It seems that it is impossible to sent SIGWINCH on virtual terminal.
https://unix.stackexchange.com/questions/16578/resizable-serial-console-window

**Comment by Wramberg** [comment]
I actually thought SIGWINCH was generated by the shell when it registers that the window was resized (with tiocswinsz). I tested this with less which seems to resize regardless. Maybe its checking for screen resize regularly ?

**Comment by randy3k** [comment]
A front program needs to either be notified or actively seek for resize event.

For the right prompt of zsh shell, it doesn't actively seek of size change, so a SIGWINCH has to be sent in order to change the environmental variable. For `less`, it seems that it checks for size before the output is printed.
