### ISSUE TITLE
Send SINGINT when `Ctrl+C` is hit

### ISSUE THREAD

**Issue by randy3k** [Wramberg/TerminalView#29]
`Ctrl+C` is not working when the program is busy.

<img width="861" alt="screen shot 2017-07-12 at 6 32 35 pm" src="https://user-images.githubusercontent.com/1690993/28142795-88726358-6730-11e7-9142-3696dc820bc1.png">

Just sending the keystroke `^C` is not enough, the front program needs to be notified by a `SIGINT`.

**Comment by Wramberg** [comment]
@randy3k are you sure theres not something wrong with your setup ? Ctrl-c works fine on Linux. I really do not think that TerminalView should be sending any signals. I think the PTY/Shell should decide which signals to send.

**Comment by Wramberg** [comment]
Maybe the way your ST3 is opened it blocks the ctrl-c signal ? That would be inherited by the shell and its processes which would result in what you see.

**Comment by randy3k** [comment]
May be a macOS issue?

**Comment by Wramberg** [comment]
Perhaps - could you check the output of

```
ps -eo pid,blocked,cmd
```

The blocked column should show if ST3 or the terminal view shell blocks any signals. I remember having the same issue in my i3 setup where dmenu (i think it was) blocked all signals. That would be inherited by ST3 and then again by the shell.

**Comment by randy3k** [comment]
not at all.
```bash
(randyimac)-~$ ps -eo pid,blocked,command | grep Sublime
81863        0 /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
81864        0 /Applications/Sublime Text.app/Contents/MacOS/plugin_host 81863
84829        0 grep --color=auto Sublime
```

**Comment by randy3k** [comment]
Oddly,... it is working now...

**Comment by randy3k** [comment]
I figure that the inconsistent behavior is due to the shells. The signal doesn't send to zsh. It has no problem to send signal to bash.

**Comment by randy3k** [comment]
Running zsh on top of bash shell fixed the signal issue.
```
    {
      "caption": "Open Terminal View - Zsh",
      "command": "terminal_view_open",
      "args"   : {"title": "Terminal (zsh)", "cmd": "/usr/local/bin/bash -l -c /usr/local/bin/zsh"},
    },
```

**Comment by Wramberg** [comment]
Great - that is the only supported setup at the moment.

Im not sure why the zsh behaves so differently (or why the pty behaves differently when attached to an zsh shell). You are welcome to look into it if you like. I just havent had the time yet.
