### ISSUE TITLE
scroll bar on macOS

### ISSUE THREAD

**Issue by randy3k** [Wramberg/TerminalView#32]
@Wramberg  There have been several attempts to set [offset][1] to remove the horizontal scroll bar. But I assume that you were testing it on a linux. On macOS, it seems that it has to be at least 3. For vertical scroll bar, it needs at least 1. Hopes it help.

```python
        nb_columns = int(pixel_width / pixel_per_char) - 3
        if nb_columns < 1:
            nb_columns = 1

        nb_rows = int(pixel_height / pixel_per_line) - 1
        if nb_rows < 1:
            nb_rows = 1
```

[1]: https://github.com/Wramberg/TerminalView/blob/483780090645c5392024c8db5a71f45c44c198bf/sublime_terminal_buffer.py#L103

**Comment by Wramberg** [comment]
You are right I have been fighting with those pesky scrollbars. At the moment I am not attempting to remove them I simply faced the fact that it is too dependent on the user setup.

I guess it could default to 1 (or 0) and I could add an option in the settings to let users decide their "margin". In that case you could set to 3 if you wanted to get rid of the vertical scrollbar.

What do you think ?

**Comment by randy3k** [comment]
I agree we should make it customizable, however it has to be conservative. In this way, most users can enjoy the scroll bar free experience. 

I have tried the default theme of Mac, it seems that -3 (horizontally) and -1 (vertically) work.

**Comment by Wramberg** [comment]
Can be configured now after 743f66de10a4e9f3de4b578163f2f502474e1489
