### ISSUE TITLE
Enhancement Proposal: Ctrl+c for copy and  Ctrl+v for paste

### ISSUE THREAD

**Issue by bfelder** [Wramberg/TerminalView#37]
@Wramberg Thank you for intense effort developing one of the most promising plugins of sublime text 3!

I like TerminalView as it allows the best terminal emulation in Sublime of all plugins I came across so far.
This is important as it makes Sublime into a full blown IDE for me, having access to python virtual environments, debugging and shell scripts.

**One feature I would like to see is to be able to copy and paste from/to TerminalView with the same keybindings as in the rest of Sublime. It is irritating to always have to switch to Ctrl+Shift+c/v.** It also block two key combinations for the same action each.

My default Linux terminal understand Ctrl+c and Ctrl+v also like any other text program.

- Ben

**Comment by Wramberg** [comment]
Hi @bfelder - I understand it can be frustrating having to switch keys when you switch into a terminalview. I assume your linux terminal maps ctrl-c to break whenever you do not have a selection ? and to copy if you do have an active selection ?

How is ctrl-v handled though ? Is it simply intercepted and not sent to the shell ?

**Comment by bfelder** [comment]
@Wramberg - Thank you for your response! I believe it is important to keep commands consistent inside Sublime. Having two different keybindings for essentially the same function is not user friendly.

I am on Linux Mint 18.2 Cinnamon. The terminal allows to adjust keybindings. By default Ctrl+c is mapped to break. However now break maps to Ctrl+Shift+c. Ctrl+c always maps to copy and Ctrl+v always to paste. This is not influenced by clipboard content.

Does this answer your questions? Do you require any other input from me?

**Comment by randy3k** [comment]
@bfelder, you could basic remap any keyboard to whatever you like. Just look at [sublime-keymap](https://github.com/Wramberg/TerminalView/blob/master/Default.sublime-keymap) file.

On my Mac, I have
```

    // Terminal view
    {
        "keys": ["super+v"], "command": "terminal_view_paste",
        "context": [{"key": "setting.terminal_view"}]
    },
    {
        "keys": ["alt+backspace"], "command": "terminal_view_keypress", "args": {"key": "backspace", "alt": true},
        "context": [{"key": "setting.terminal_view"}]
    },
    {
        "keys": ["alt+left"], "command": "terminal_view_keypress", "args": {"key": "b", "alt": true},
        "context": [{"key": "setting.terminal_view"}]
    },
    {
        "keys": ["alt+right"], "command": "terminal_view_keypress", "args": {"key": "f", "alt": true},
        "context": [{"key": "setting.terminal_view"}]
    },
    {
        "keys": ["super+left"], "command": "terminal_view_keypress", "args": {"key": "a", "ctrl": true},
        "context": [{"key": "setting.terminal_view"}]
    },
    {
        "keys": ["super+right"], "command": "terminal_view_keypress", "args": {"key": "e", "ctrl": true},
        "context": [{"key": "setting.terminal_view"}]
    }
```

**Comment by bfelder** [comment]
@randy3k Thank you for your response and the example keymap! Also, thank you for your ProjectManager plugin, as it fills an important gap in Sublime's functionality!

I have been using Sublime only for a short period of time as of this day. Of course, I know how to rebind keys. I was not aware of the **context parameter** though. **Indeed I was afraid remapping Ctrl+c/Ctrl+v would deny that function for the rest of Sublime.**

I am going to test it out tomorrow.

This leads this issue to the question which keys should be the default ones?
Ctrl+c/v or Ctr+Shift+c/v.
Do we want to keep Sublime's key bindings internally consistent or do we want to stick to how the standard terminal key bindings?

An almost philosophical question.

**I believe it would be best to keep TerminalView's default keymap as it is.
Still, we might include alternative bindings for Ctr+c/v in the readme or elsewhere accessible.**

What are your thoughts on this? 
_I offer to do a PR for such updated readme._

**Comment by Wramberg** [comment]
@bfelder if you simply want to rebind keys you can do it as @randy3k suggest. I think it's mentioned pretty clearly in the readme already ? It states the default keybindings and that they can be changed through the menu or the command palette. In your case I suggest you add something like the following in your custom keymap.

```
{"keys": ["ctrl+c"], "command": "terminal_view_copy", "context": [{"key": "setting.terminal_view"}]},
{"keys": ["ctrl+v"], "command": "terminal_view_paste", "context": [{"key": "setting.terminal_view"}]},
{"keys": ["ctrl+shift+c"], "command": "terminal_view_keypress", "args": {"key": "c", "ctrl": true}, "context": [{"key": "setting.terminal_view"}]},
{"keys": ["ctrl+shift+v"], "command": "terminal_view_keypress", "args": {"key": "v", "ctrl": true}, "context": [{"key": "setting.terminal_view"}]},
```

I agree it would be best to keep the keybindings in terminalview as they are. I think keybindings like ctrl+c are expected to break in a terminal.

I guess the readme could be more clear about rebinding as right now it only discusses missing keybindings and overriding.

**Comment by bfelder** [comment]
> I guess the readme could be more clear about rebinding as right now it only discusses missing keybindings and overriding.
 
I have just opened a pull request in this regard. It is a suggested extension to the readme.
Note also that the key bindings for Mac OS need to be adapted, as I do not know Mac OS.

**Comment by Wramberg** [comment]
Ill close this issue and discussion can continue in the PR.
