### ISSUE TITLE
Open terminal with working directory set as project root

### ISSUE THREAD

**Issue by mandeep** [Wramberg/TerminalView#41]
```
OS: OSX
ST3: Build 3126
Bash: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
```
When opening a bash terminal from command palette, the terminal's current working directory seems to be set to the same directory as the file you're currently working on. According to the docstring here: https://github.com/Wramberg/TerminalView/blob/master/TerminalView.py#L31 shouldn't the path be set to the project root? If this is intended behavior, what's the best way to set TerminalView to always open in the project root? A key binding with args?

Thanks for an awesome plugin btw.

**Comment by rwols** [comment]
Hi Mandeep,

You can change the current working directory by adding a new sublime command to your `.sublime-commands` with an explicit `cwd` argument. For instance,

```json
[
  {
    "caption": "Terminal View: Open Bash Terminal (in project base folder)",
    "command": "terminal_view_open",
    "args"   : {"title": "Terminal (bash)", "cmd": "/bin/bash -l", "cwd": "${folder}"},
  }
]
```
Save this as `TerminalView.sublime-commands` in your Packages/User directory.

It seems the docs have not been updated.

**Comment by rwols** [comment]
It seems I spoke too soon. Substituting variables doesn't work. I'll turn this into a PR.

**Comment by Wramberg** [comment]
Pulled in @rwols PR. Should be able to change the cwd snippet after 2ee3a28b97fc786836035c8307dbc972e0a04cb6 has been included in a release.

**Comment by Wramberg** [comment]
I'll close this for now. @mandeep stay tuned for an update in the near future. Feel free to pop back in if you experience any further issues :-)

**Comment by mandeep** [comment]
Was this supposed to be in the 0.5.0 release? Using the custom command doesn't seem to change anything.

**Comment by mandeep** [comment]
After playing around it seems that the project_path and folder commands work, it's just not what I was looking for.

If I'm working on a file at /home/user/Repos/some-project/some_project/file.py, how do I open a terminal with the some-project directory as the cwd? Is there a specific substitution I can make?

Thanks for all the help.

**Comment by rwols** [comment]
Where does your `.sublime-project` live?

**Comment by megadr01d** [comment]
> If you always use sublime in project mode, you could also opt for `${project_path}` instead of `${folder}`

I'm also interested in this. Help me and @mandeep figure this out...

My `.sublime-project` file has the path set to

```
"path": "/Users/soulitude/admin"
```

If I call the default **Terminal View: Open Bash Terminal** command like so

```
"args": {"title": "Terminal (bash)", "cmd": "/bin/bash -l"}
```

while viewing `~/admin/dev/note/notepad.txt`, it opens the terminal on `~/admin/dev/note`.

If I call @rwols command suggestion with

```
"args": {"title": "Terminal (bash)", "cmd": "/bin/bash -l", "cwd": "${folder}"}
```

while viewing `~/admin/dev/note/notepad.txt`, it opens the terminal on `~/admin`.

If I call @rwols command suggestion with

```
"args"   : {"title": "Terminal (bash)", "cmd": "/bin/bash -l", "cwd": "${project_path}"}
```

while viewing `~/admin/dev/note/notepad.txt`, it opens the terminal on `~/Library/Application Support/Sublime Text 3/Projects`, which is where I keep my projects.

`${folder}` does what I want but `${project_path}` seems ambiguous because I thought it refered to the path set in the `.sublime-project` file, eg. `"path": "/Users/soulitude/admin"`.

**Comment by randy3k** [comment]
If I understand correctly, `${folder}` is the first folder of the current window. You just have to make sure the first folder of the window is `~/admin/dev/note`.

**Comment by mandeep** [comment]
I changed my workflow and now ``${folder}`` works for what I want. 

Before, I had all of my repositories open in the project so ``${folder}`` would go to the directory containing all of my repositories instead of the repository directory that was being worked on.
