### ISSUE TITLE
0.5.0 release candidate testing

### ISSUE THREAD

**Issue by Wramberg** [Wramberg/TerminalView#48]
Due to the increasing amount of users and diverse environments testing is a lot work if we are to avoid regressions. For this reason, I'm considering introducing release candidates. I want this to be an opportunity for everyone to help sort out any issues before a release goes out.

I do not expect people to have time but if you do it would be much appreciated. All I'm asking is that you check out the 0.5.0 branch https://github.com/Wramberg/TerminalView/tree/0.5.0, use it for a little while and report back any issues you may encounter.

@rwols @randy3k I hope you have time to help do some general macOS testing and specific testing of the terminal_view_send_string and terminal_view_exec commands (if you haven't already ;-)).

@bfelder If you have time to help as well that would be nice.

Like I said just use TerminalView like you normally would - hopefully it won't be too much of a bother that way :-)

If anyone else sees this and want to help out let me know and I will mention you next time I have a release candidate.

**Comment by bfelder** [comment]
Great! I have a look at it tomorrow. As mentioned I run Linux Mint 18.2 which is essentially a recent release of Ubuntu in its core.

**Comment by randy3k** [comment]
Great job! `terminal_view_send_string` is working correctly.

**Comment by Wramberg** [comment]
Thanks guys. Should probably mention I plan to release 0.5.0 towards the end of next week. Should hopefully be enough time to test it a bit.

**Comment by bfelder** [comment]
@Wramberg Works like a charm! :+1: 
I tested usual command like `echo 3`, `python my_python_file.py` same output as before.
I have also written a companion plugin to TerminalView which automatically open a virtual environment if such a path is present with a project settings file. This also works as before.
I now tested with `htop`. A system monitor providing you with live updates on cpu load, network traffic etc ... Importantly this **output is colored**. And indeed TerminalView gave me a beautiful color terminal!
(Admittedly I did not test the previous version of TerminalView with htop. So, I can not say whether this is new.) 

Let me know if you need any other test specifically.

**Comment by rwols** [comment]
There's nothing about `terminal_view_send_string` in the readme, shouldn't there a little section devoted to it?

**Comment by bfelder** [comment]
Even pudb works fine in TerminalView. This is the first time a python debugger runs find in Sublime.
Hence, @Wramberg single-handedly transformed a common editor into full-blown python IDE. :)

Still the color scheme of my system's shell is not transferred to TerminalView. The standard text is all white.
See closed issue [https://github.com/Wramberg/TerminalView/issues/50](https://github.com/Wramberg/TerminalView/issues/50)

**Comment by rwols** [comment]
@bfelder https://github.com/Wramberg/TerminalView/pull/53 should liven up the colors 😄

**Comment by randy3k** [comment]
@bfelder agree, I have been waiting a working terminal for so.... long.

**Comment by bfelder** [comment]
@rwols to the rescue. I like to have candle light dinner with Marianna!

@randy3k a terminal as a fundamentally enabling tool opens up so many great opportunities to integrate useful features into sublime. I am particularly fond of the idea to integrate a minimal python debugger with 
TerminalView. Something simple, just wrapping ipdb or bpdb, but using both the editor view to indicate current line and terminal view for accepting commands and display of variable values.

**Comment by Wramberg** [comment]
> There's nothing about terminal_view_send_string in the readme, shouldn't there a little section devoted to it?

Yea I should probably include a bit about it. Think Ill do that and then release it as soon as I find time.

**Comment by bfelder** [comment]
@Wramberg Color might be of low priority right now.
Still, let me tell you that my normal bash indeed features color. 

The most important aspect is to color the prompt (unchangeable) differently from user input (changeable) for easier telling them apart.

Switching to another shell is no option for me, regarding how deeply integrated bash is with my Linux distro.

**Comment by Wramberg** [comment]
> Still, let me tell you that my normal bash indeed features color.

Probably because your terminal sets TERM to xterm or something.



> Switching to another shell is no option for me

In that case you can look into changing your prompt manually. https://www.cyberciti.biz/faq/bash-shell-change-the-color-of-my-shell-prompt-under-linux-or-unix/

**Comment by bfelder** [comment]
@Wramberg Thanks for the link a thousand times. The command `export PS1="\e[0;31m[\u@\h \W]\$ \e[m "` not only colors the prompt but also shortens the path, making the prompt much tidier.

I use that as an arg to the TerminalView command until xterm will get integrated into TerminalView.
(Of course, I am also going to checkout @rwols color packages. Though you suggest they may not work.)

**Comment by Wramberg** [comment]
No problem :-) I think @rwols PR will work just fine. But it only changes text that is already colored to another color - it won't add new colors anywhere (I think this is intended).

**Comment by rwols** [comment]
Yeah, that PR attempts to assign colors of the current scheme to the 8 basic terminal colors black, white, red, blue, green, cyan, magenta and yellow. It doesn't extend to 256 or even 16 colors.

**Comment by Wramberg** [comment]
0.5.0 is now live. Thanks for helping out everyone. Seems like 0.6 is already going to include a lot of new exciting things :-)
