### ISSUE TITLE
Feature Request: make settings for zsh

### ISSUE THREAD

**Issue by unknownuser88** [Wramberg/TerminalView#5]
It will great if plugin will have option for `"/bin/zsh"` `"/bin/bash" ` etc

**Comment by Wramberg** [comment]
Should be possible after 86835722780035adda6ceb12edf4ed8785f96c47 but keep in mind that only bash is tested. Alternatively you can always run "/bin/zsh" manually in the bash terminal of course - that should work just as well as bash.
