### ISSUE TITLE
More lively default color scheme.

### ISSUE THREAD

**Issue by bfelder** [Wramberg/TerminalView#50]
I like to have a more lively default color scheme. Currently, it is all white font.

It should look more like this:
[Sexy Bash Prompt](https://raw.githubusercontent.com/twolfson/sexy-bash-prompt/master/screenshot.png) ;-)

At least '$' should be colored to separate user input from all the stuff before it.

Low prio, though. ;-)

**Comment by Wramberg** [comment]
That is the default color scheme of the bash shell - nothing I can do to change that. It becomes a bit better once we support TERM=xterm-256color. Regardless TerminalView should ship with default config and let users decide if they want to install sexy bash prompt or zsh with all its fancy color themes ;-)

We could alter the PS1 env variable (https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html) but again thats something users should do in their bash_profile not something a Terminal should be in charge of.
