### ISSUE TITLE
Weird text in terminal

### ISSUE THREAD

**Issue by alexbet** [Wramberg/TerminalView#54]
I am gettin the weird things all over the place. I read the common problems section in your description and ran the command, but the TERM is set to linux it seems, yet I still get the weird thinks printed. Here is a copy of the printout:

`133;C;133;D;11337;RemoteHost=AlexBet@AlexBets-Mac-Pro.local1337;CurrentDir=/Volumes/ServerWebs/Sites/AlexBet/modules.v5133;AAlexBets-Mac-Pro:modules.v5 Al
exBet$ 133;B                                                                                                                                              
133;C;133;D;11337;RemoteHost=AlexBet@AlexBets-Mac-Pro.local1337;CurrentDir=/Volumes/ServerWebs/Sites/AlexBet/modules.v5133;AAlexBets-Mac-Pro:modules.v5 Al
exBet$ 133;B                                                                                                                                              
133;C;133;D;11337;RemoteHost=AlexBet@AlexBets-Mac-Pro.local1337;CurrentDir=/Volumes/ServerWebs/Sites/AlexBet/modules.v5133;AAlexBets-Mac-Pro:modules.v5 Al
exBet$ 133;B                                                                                                                                              
133;C;133;D;11337;RemoteHost=AlexBet@AlexBets-Mac-Pro.local1337;CurrentDir=/Volumes/ServerWebs/Sites/AlexBet/modules.v5133;AAlexBets-Mac-Pro:modules.v5 Al
exBet$ 133;B                                                                                                                                              
133;C;133;D;11337;RemoteHost=AlexBet@AlexBets-Mac-Pro.local1337;CurrentDir=/Volumes/ServerWebs/Sites/AlexBet/modules.v5133;AAlexBets-Mac-Pro:modules.v5 Al
exBet$ 133;B                                                                                                                                              
133;C;133;D;11337;RemoteHost=AlexBet@AlexBets-Mac-Pro.local1337;CurrentDir=/Volumes/ServerWebs/Sites/AlexBet/modules.v5133;AAlexBets-Mac-Pro:modules.v5 Al
exBet$ 133;Benv | grep TERM                                                                                                                               
133;C;TERM=linux                                                                                                                                          
ITERM_ORIG_PS1=\h:\W \u\$                                                                                                                                 
ITERM_PREV_PS1=\[133;D;$?1337;RemoteHost=AlexBet@AlexBets-Mac-Pro.local1337;CurrentDir=/Volumes/ServerWebs/Sites/AlexBet/modules.v5133;A\]\h:\W \u\$ \[133
;B\]                           `

You can see where I ran the "env | grep TERM" command and the result. Hope you can fix this. Thanks!

**Comment by Wramberg** [comment]
Looks like an iTerm issue. Unfortunately some applications do not care what type of terminal is connected and simply assumes xterm capabilities. Current devel plans include support for xterm but it requires changing the underlying terminal emulator so it's not easily done. Until then only fix is to disable iTerm when using TerminalView - if that's possible I don;'t know (not mac user).

**Comment by alexbet** [comment]
Hmmmm, that is weird, because it works on my laptop with iTerm, but it doesn't work on my desktop with iTerm. How could that be?

**Comment by Wramberg** [comment]
Maybe I should clarify, I'm not saying that it is an iTerm issue - it just looks like it. Could also be some other third party app messing with your bash prompt. I think @randy3k has seen something similar maybe he can pinpoint it. My best suggestion is to try to disable e.g. iTerm or other third party apps to see if that helps.

Do you normaly use bash ? Otherwise you could also try another shell.

**Comment by randy3k** [comment]
@alexbet 

try replacing the source command of the iTerm script in your `.bash_profile` or `.bashrc` by the following
```
if [ "$TERM" = "xterm-256color" ] && [ -z "$INSIDE_EMACS" ]; then
    [ -f "~/.iterm2_shell_integration.bash" ] && source ~/.iterm2_shell_integration.bash
fi

```

**Comment by Wramberg** [comment]
> Hmmmm, that is weird, because it works on my laptop with iTerm, but it doesn't work on my desktop with iTerm. How could that be?

Sorry I think i misunderstood you. Are you confirming that turning off iTerm fixes the issue ?

**Comment by randy3k** [comment]
I am pretty sure it is caused by the `.iterm2_shell_integration.bash` given the output of the console. Disabling sourcing the script should immediately fix the issue. The matter is to figure out where the `source` command is hidden (most probably is `.bash_profile`).

**Comment by randy3k** [comment]
The root of the issue is because pyte 0.5.2 does not support OSC sequence, I tried switching to pyte 0.7.0-dev and it fixed the issue. However, I couldn't figure out how to fix the resize-window issue.

**Comment by alexbet** [comment]
@randy3k - Adding that code in the .bash_profile file fixed the issue. Thank you!

**Comment by kukharchuk** [comment]
@randy3k Thx
