### ISSUE TITLE
Hide Minimap?

### ISSUE THREAD

**Issue by rwols** [Wramberg/TerminalView#58]
Since the virtual screen uses the bounds of the view anyway, I don't see any point in displaying the minimap.

**Comment by rwols** [comment]
I attempted an implementation for this but it seems you must set the minimap visibility via the window object. There's no way to subscribe to an event that tells you if the minimap visibility changed, so while you can remember the last setting in a view event listener there's no way to listen to a changing event. I suggest to make this low priority.

**Comment by Wramberg** [comment]
As far as I know its not possible for at plugin to control the minimap ?

**Comment by rwols** [comment]
It's available under `view.window().set_minimap_visible(True/False)` and `view.window().is_minimap_visible()`. The problem then is that the minimap being visible is a property of the window, for our purposes it should have been a property of the view.

**Comment by Wramberg** [comment]
Oh didn't know that :-) But yea - we probably shouldn't mess with the window.

**Comment by Wramberg** [comment]
I guess we can close this.
