### ISSUE TITLE
Some background colors / functionality missing

### ISSUE THREAD

**Issue by rwols** [Wramberg/TerminalView#60]
* macOS 10.12
* ST3 build 3142
* fish 2.6

<img width="769" alt="schermafbeelding 2017-08-14 om 18 54 09" src="https://user-images.githubusercontent.com/2431823/29282205-446d3816-8122-11e7-93e2-16a3c3234f82.png">
<img width="767" alt="schermafbeelding 2017-08-14 om 18 54 33" src="https://user-images.githubusercontent.com/2431823/29282206-449553d2-8122-11e7-9170-a34f37e47240.png">

When I type `ls -`, and then press <kbd>tab</kbd>, fish presents me with all of the possible switches. Pressing <kbd>tab</kbd> a few more times selects different options. The currently selected option is highlighted with a different background as you can see in the screenshot. This differently colored background is not present in TerminalView so I cannot see which option I currently have selected. The top screenshot is TerminalView, the bottom screenshot is the Terminal app from macOS.

**Comment by randy3k** [comment]
It works for zsh

<img width="443" alt="screen shot 2017-08-14 at 2 06 32 pm" src="https://user-images.githubusercontent.com/1690993/29284709-cc864504-80f9-11e7-8551-483a2f1972c7.png">

**Comment by randy3k** [comment]
May be a 256 color issue?

**Comment by rwols** [comment]
Yeah, I feel like that's the core issue. Just thought I'd mention it.

**Comment by Wramberg** [comment]
Pretty sure this goes under the 256 color feature so have to wait for some more gateone testing ;-)
