### ISSUE TITLE
Introducing ShellVE - Automatic Python VEs in TerminalView

### ISSUE THREAD

**Issue by pyking2** [Wramberg/TerminalView#61]
I have written a very cool little companion plugin to TerminalView, I named [ShellVE](https://github.com/bfelder/ShellVE).

It automatically opens a TerminalView tab with the python virtual environments of a project already initialised. I have always loved how PyCharm just associates a project with a particular virtual environment, so you never have to worry whether your files are run by the correct one.

ShellVE imitates that close linkage between a project and virtual environment while providing a greater flexibility than Sublime's build system. (E.g. you may install packages to the VE via pip)

I thought this is the best place to let you know as here the TerminalView guys gather. :)

Find it here: [ShellVE](https://github.com/bfelder/ShellVE)

**Comment by Wramberg** [comment]
Interesting plugin @bfelder. Im glad to see you have use for my plugin :-) :+1:

**Comment by bfelder** [comment]
@Wramberg And I am sure I am not the only one. :+1: 

You may leave this issue open as long as you consider fit.
Once it has been accepted into the PackageControl channel, I am going to introduce it on Subline Forum. The issue may be closed then.

**Comment by pyking2** [comment]
ShellVE is now live on PackageControl.io. [Here](https://packagecontrol.io/packages/ShellVE)
(The readme page is screwed up, I have to check what is going on there.)

@Wramberg I'll close this issue. You may later decide to mention ShellVE in the README.
