### ISSUE TITLE
Keyboard Scrolling Broken

### ISSUE THREAD

**Issue by SMores** [Wramberg/TerminalView#66]
Using Sublime Text 3 on macOS
```
smoores$ bash --version                                                                        
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)   
```

I added the following to my Sublime Text Key Bindings: 
```
{"keys": ["shift+alt+up"], "command": "terminal_view_scroll", "args": {"forward": false}, "context": [{"key": "setting.terminal_view"}]},
{"keys": ["shift+alt+down"], "command": "terminal_view_scroll", "args": {"forward": true}, "context": [{"key": "setting.terminal_view"}]},
```

But when using them in TerminalView, the up command jumps all of the way to the top of the history, and then the down command jumps not quite to the bottom, leaving me in a state where there's no way to see the current prompt. If I press enter, I get a prompt (usually at the bottom?), but all of the history that was below it seems to be gone.

I have some screenshots if you think they'll be helpful, but they're honestly a bit confusing to look at.

**Comment by megadr01d** [comment]
Works fine here on ST Dev 3142, OS X 10.11.
Did you change the `terminal_view_scroll_ratio` value in TerminalView's settings?

**Comment by SMores** [comment]
Yeeeeup that was it. Thanks!
