### ISSUE TITLE
A workaround for .bash_profile file with coloured prompt?

### ISSUE THREAD

**Issue by stevage** [Wramberg/TerminalView#68]
>Before submitting a bug please ensure you do not have a .bash_profile file or similar that changes the value of the TERM environment variable. This is set to "linux" by the plugin and must NOT be changed.

I do indeed have a .bash_profile file, which sets a coloured prompt (dark grey text - my terminal is pale yellow):

`export PS1='\h \[\e[1;34m\]\w\[\e[m\] \[\e[1;30m\]\$\[\e[m\] \[\e[0;30m\]'`

In TerminalView this is no good, as my colour scheme has black background (so the text is dark grey on black).

Is there a workaround? Either:

- A script that would always be run when opening TerminalView (so I could override the values in .bash_profile)
- Avoid running .bash_profile somehow.

**Comment by stevage** [comment]
Well, I guess one workaround is this in my TerminalView.sublime-setings - User:

```
{
    "terminal_view_show_colors": false
}
```

**Comment by Wramberg** [comment]
Hey @stevage 

You can change the cmd argument when opening terminal view so bash does not read /etc/profile, .bash_profile or similar. Simply drop the `-l`.

```
{ "keys": ["ctrl+alt+t"], "command": "terminal_view_open", "args": {"cmd": "/bin/bash", "title": "Bash Terminal"}},
```

Alternatively (I have never done this myself) I guess you could also set an environment var before launching bash like

```
{ "keys": ["ctrl+alt+t"], "command": "terminal_view_open", "args": {"cmd": "TERMINALVIEW=y /bin/bash -l", "title": "Bash Terminal"}},
```

and then add an if sentence around your prompt in your bash_profile - something like

```
if [ "$TERMINALVIEW" = "y" ]; then
    ....
fi
```

Finally you are also free to change the color scheme of the terminal view (like described in the readme :-))

I don't have time to test anything at the moment but hopefully this helps. Let me know how it goes.

**Comment by Wramberg** [comment]
Any updates on this @stevage ?

**Comment by stevage** [comment]
Thanks! Somehow I missed this original notification. I think those are all reasonable options, but I think I will actually just switch my iTerm colour scheme to use a dark background, and then use a colour scheme that works in both iTerm and TerminalView. I don't have any particular need for the pale yellow background I have at the moment.

Mostly using TV on another machine with default iTerm colours, and it works great. Really, really like it - thank you!

**Comment by Wramberg** [comment]
Glad you like it :+1: Ill go ahead and close this :-)
