### ISSUE TITLE
Start TerminalView in the working directory I'm currently in for ST 3

### ISSUE THREAD

**Issue by AlexWang-16** [Wramberg/TerminalView#78]
It would be a cool feature to have if TerminalView can be configured to start in the current working directory for the project that I'm working on currently in ST3. Does anyone know if it is possible to configure this?

**Comment by rwols** [comment]
See: https://github.com/Wramberg/TerminalView/issues/41

**Comment by AlexWang-16** [comment]
That's exactly what I was looking for. Thanks!
