### ISSUE TITLE
The road to a stable fish and zsh

### ISSUE THREAD

**Issue by rwols** [Wramberg/TerminalView#8]
~When I try to use the fish shell, the view opens and then closes immediately. Any ideas how this can be solved? I tried it on my Ubuntu machine and the same thing happens.~

* [x] Bash 4.4 Ubuntu 16.04
* [x] Bash 4.4 macOS 10.12
* [x] Bash 3.2 macOS 10.12
* [x] Z-Shell 5.3.1 macOS 10.12
* [x] Z-Shell 5.1.1 Ubuntu 16.04
* [x] Z-Shell 5.3.1 with oh-my-zsh macOS 10.12
* [x] Z-Shell 5.1.1 with oh-my-zsh Ubuntu 16.04
* [x] Fish 2.6.0 macOS 10.12
* [x] Fish 2.5.0 Ubuntu 16.04

**Comment by Wramberg** [comment]
I don't have any ideas as to why it would close right away. Maybe something to do with the resizing ioctl but I havent looked into it. 

I'm starting to think that maybe a better approach would be to add support for running a second command automatically after bash is started. This would probably work fine for most people since they have bash anyway - but they would be able to specify that e.g. fish shell should be run right after starting.

For the people who want to avoid bash completely we can keep the option open for choosing another shell - but I think this should be left as a last resort as it seems to cause some problems (just tried zsh which seems to work fine except that ignores the ctrl-c (ETX) keycode for some reason).

**Comment by rwols** [comment]
When I try zsh with `/bin/zsh -l`, I get these messages in the buffer every time I press <kbd>Enter</kbd>:
```
echotc: no such capability: UP
echotc: no such capability: DO
```

I can start fish by using `/bin/sh -c -- /usr/local/bin/fish -l`; seems to work fine.

**Comment by rwols** [comment]
Ideally, the default `cmd` would be to use `"%s -l" % os.environ["SHELL"]` but that seems to be unreliable at this point. I think if you fix the zsh and fish issues you accounted for 99% of your potential users.

**Comment by Wramberg** [comment]
Try the newest commit on `devel` bd965530f5d5b016a49fead9a1530ca0b6a7351d. Broke alot of unittests Ill have to check up on but should work well with both fish and zsh (hopefully).

@randy3k feel free to test zsh if you got time. Should work with signals, resize, etc. without starting it through bash.

**Comment by randy3k** [comment]
I don't know if it is true, [pty](https://github.com/python/cpython/blob/3.3/Lib/pty.py#L3) says it doesn't handle signals.

**Comment by rwols** [comment]
Can confirm that running a bare `/usr/local/bin/fish` works for me. Awesome!

**Comment by randy3k** [comment]
So it looks like what is said in pty is not correct

**Comment by rwols** [comment]
When I run a bare `/usr/local/bin/zsh`, I do still get these messages:

```
echotc: no such capability: UP                                                                                           
echotc: no such capability: DO 
```
So fish seems to work fine on macOS, zsh seems unfixed.

**Comment by randy3k** [comment]
I am not sure why @rwols got those errors, but it works fine for me. My zsh version is 5.3.1.

**Comment by Wramberg** [comment]
I don't get the echotc message either. Will look a bit more into it.

**Comment by rwols** [comment]
I have zsh version 5.3.1, I tried setting my default shell to zsh, but I still get these messages. They appear just before I can type a command again. It might be a problem on my side if it works for @randy3k 

![schermafbeelding 2017-08-03 om 12 33 13](https://user-images.githubusercontent.com/2431823/28918012-ffda6936-7847-11e7-9312-7e1d99ec080e.png)

**Comment by Wramberg** [comment]
My best guess is it has something to do with terminfo entries. Maybe it fails to a terminfo entry for those capabilities or something.

**Comment by rwols** [comment]
I don't have any knowledge of terminfo, but I'm learning as I go :). There are some files in /usr/share/terminfo but they seem to be binary files. I learned I can use the program `infocmp` to read those files (I think?). Here is a dump of that:

```
rwols@Air-van-Raoul ~/dev> man terminfo
rwols@Air-van-Raoul ~/dev> infocmp vt100
#	Reconstructed via infocmp from file: /usr/share/terminfo/76/vt100
vt100|vt100-am|dec vt100 (w/advanced video),
	am, mc5i, msgr, xenl, xon,
	cols#80, it#8, lines#24, vt#3,
	acsc=``aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m$<2>, bold=\E[1m$<2>,
	clear=\E[H\E[J$<50>, cr=^M, csr=\E[%i%p1%d;%p2%dr,
	cub=\E[%p1%dD, cub1=^H, cud=\E[%p1%dB, cud1=^J,
	cuf=\E[%p1%dC, cuf1=\E[C$<2>,
	cup=\E[%i%p1%d;%p2%dH$<5>, cuu=\E[%p1%dA,
	cuu1=\E[A$<2>, ed=\E[J$<50>, el=\E[K$<3>, el1=\E[1K$<3>,
	enacs=\E(B\E)0, home=\E[H, ht=^I, hts=\EH, ind=^J, ka1=\EOq,
	ka3=\EOs, kb2=\EOr, kbs=^H, kc1=\EOp, kc3=\EOn, kcub1=\EOD,
	kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA, kent=\EOM, kf0=\EOy,
	kf1=\EOP, kf10=\EOx, kf2=\EOQ, kf3=\EOR, kf4=\EOS, kf5=\EOt,
	kf6=\EOu, kf7=\EOv, kf8=\EOl, kf9=\EOw, lf1=pf1, lf2=pf2,
	lf3=pf3, lf4=pf4, mc0=\E[0i, mc4=\E[4i, mc5=\E[5i, rc=\E8,
	rev=\E[7m$<2>, ri=\EM$<5>, rmacs=^O, rmam=\E[?7l,
	rmkx=\E[?1l\E>, rmso=\E[m$<2>, rmul=\E[m$<2>,
	rs2=\E>\E[?3l\E[?4l\E[?5l\E[?7h\E[?8h, sc=\E7,
	sgr=\E[0%?%p1%p6%|%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;m%?%p9%t\016%e\017%;$<2>,
	sgr0=\E[m\017$<2>, smacs=^N, smam=\E[?7h, smkx=\E[?1h\E=,
	smso=\E[7m$<2>, smul=\E[4m$<2>, tbc=\E[3g,
rwols@Air-van-Raoul ~/dev> infocmp linux
#	Reconstructed via infocmp from file: /usr/share/terminfo/6c/linux
linux|linux console,
	am, bce, ccc, eo, mir, msgr, xenl, xon,
	colors#8, it#8, ncv#18, pairs#64,
	acsc=+\020\,\021-\030.^Y0\333`\004a\261f\370g\361h\260i\316j\331k\277l\332m\300n\305o~p\304q\304r\304s_t\303u\264v\301w\302x\263y\363z\362{\343|\330}\234~\376,
	bel=^G, blink=\E[5m, bold=\E[1m, civis=\E[?25l\E[?1c,
	clear=\E[H\E[J, cnorm=\E[?25h\E[?0c, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub1=^H, cud1=^J, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu1=\E[A, cvvis=\E[?25h\E[?8c,
	dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m, dl=\E[%p1%dM,
	dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K, el1=\E[1K,
	flash=\E[?5h\E[?5l$<200/>, home=\E[H, hpa=\E[%i%p1%dG,
	ht=^I, hts=\EH, ich=\E[%p1%d@, ich1=\E[@, il=\E[%p1%dL,
	il1=\E[L, ind=^J,
	initc=\E]P%p1%x%p2%{256}%*%{1000}%/%02x%p3%{256}%*%{1000}%/%02x%p4%{256}%*%{1000}%/%02x,
	kb2=\E[G, kbs=\177, kcbt=\E[Z, kcub1=\E[D, kcud1=\E[B,
	kcuf1=\E[C, kcuu1=\E[A, kdch1=\E[3~, kend=\E[4~, kf1=\E[[A,
	kf10=\E[21~, kf11=\E[23~, kf12=\E[24~, kf13=\E[25~,
	kf14=\E[26~, kf15=\E[28~, kf16=\E[29~, kf17=\E[31~,
	kf18=\E[32~, kf19=\E[33~, kf2=\E[[B, kf20=\E[34~,
	kf3=\E[[C, kf4=\E[[D, kf5=\E[[E, kf6=\E[17~, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
	kmous=\E[M, knp=\E[6~, kpp=\E[5~, kspd=^Z, nel=^M^J, oc=\E]R,
	op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=\E[10m,
	rmam=\E[?7l, rmir=\E[4l, rmpch=\E[10m, rmso=\E[27m,
	rmul=\E[24m, rs1=\Ec\E]R, sc=\E7, setab=\E[4%p1%dm,
	setaf=\E[3%p1%dm,
	sgr=\E[0;10%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p6%t;1%;%?%p7%t;8%;%?%p9%t;11%;m,
	sgr0=\E[0;10m, smacs=\E[11m, smam=\E[?7h, smir=\E[4h,
	smpch=\E[11m, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
	u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?6c, u9=\E[c,
	vpa=\E[%i%p1%dd,
```
I hope this can be of any use.

**Comment by Wramberg** [comment]
Still just guessing here but I think for some reason your zsh is complaning that the terminal has no `UP` or `DO` capabilities. Don't know what they do, I don't have those either.

**Comment by Wramberg** [comment]
@rwols could you check if you have anything that might cause this in your ~/.zshrc file ?

or maybe in some of the many files zsh sources:

```
When starting Zsh, it will source the following files in this order by default:
/etc/zsh/zshenv Used for setting system-wide environment variables; it should not contain commands that produce output or assume the shell is attached to a tty. This file will always be sourced, this cannot be overridden.
$ZDOTDIR/.zshenv Used for setting user's environment variables; it should not contain commands that produce output or assume the shell is attached to a tty. This file will always be sourced.
/etc/zsh/zprofile Used for executing commands at start, will be sourced when starting as a login shell. Please note that on Arch Linux, by default it contains one line which source the /etc/profile.
/etc/profile This file should be sourced by all Bourne-compatible shells upon login: it sets up $PATH and other environment variables and application-specific (/etc/profile.d/*.sh) settings upon login.
$ZDOTDIR/.zprofile Used for executing user's commands at start, will be sourced when starting as a login shell.
/etc/zsh/zshrc Used for setting interactive shell configuration and executing commands, will be sourced when starting as an interactive shell.
$ZDOTDIR/.zshrc Used for setting user's interactive shell configuration and executing commands, will be sourced when starting as an interactive shell.
/etc/zsh/zlogin Used for executing commands at ending of initial progress, will be sourced when starting as a login shell.
$ZDOTDIR/.zlogin Used for executing user's commands at ending of initial progress, will be sourced when starting as a login shell.
$ZDOTDIR/.zlogout Will be sourced when a login shell exits.
/etc/zsh/zlogout Will be sourced when a login shell exits.
```

Source: https://wiki.archlinux.org/index.php/zsh

**Comment by rwols** [comment]
Okay. I uninstalled oh-my-zsh, and now I don't get these messages anymore (hooray). Can anyone confirm if, when they install oh-my-zsh, they get these UP and DO messages? The theme I used was called [robbyrussell](https://github.com/robbyrussell/oh-my-zsh/wiki/themes), maybe the problem is in there.

**Comment by randy3k** [comment]
I am also on macOS 10.12

**Comment by Wramberg** [comment]
Interesting - seems like the avit theme uses UP and DO to render the prompt. Couldn't grep them any other place in oh-my-zsh.

https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/avit.zsh-theme#L9

**Comment by Wramberg** [comment]
If you open a zsh session in e.g. mate-terminal and run `echotc UP 1` it moves everything up. So echotc must have some kind of idea about the capabilities of the terminal where TerminalView does not support moving everything up/down.

Don't know where these capabilities are listed though.

**Comment by Wramberg** [comment]
Opening a native zsh shell and running `echotc UP 1` or `echotc DO 1` works fine for me in TerminalView using zsh 5.1.1 on Ubuntu 16.04. Ill try installing oh-my-zsh and see if it still works.

**Comment by Wramberg** [comment]
Installed oh-my-zsh in newest version from master

```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```

everything still works. Changed theme from `robbyrussel` to `avit` and still not seeing the echotc message. Calling `echotc UP/DOWN 1` manually also works. Think its pretty safe to say this works for me.

**Comment by rwols** [comment]
I reinstalled oh-my-zsh and I don't get the UP/DO messages anymore. This feels very strange, but I think it's safe to say that it was something on my end.

**Comment by Wramberg** [comment]
That is quite - but I'm happy it works !

**Comment by Wramberg** [comment]
I guess its ok to close this now ? Im not going to make any big announcements about support just yet - maybe in 0.6 :-)

**Comment by rwols** [comment]
Yeah, I'm happily enjoying fish at the moment, I think we did enough testing.

**Comment by monday0rsunday** [comment]
> I reinstalled oh-my-zsh and I don't get the UP/DO messages anymore

I reinstall oh-my-zsh and I don't get the UP/DO messages too, but when I change my theme to avit, those messages come again

**Comment by ELJEFEonAtrunk** [comment]
There is a roughway to get rid of  these UP/DO messages when using avit.
Find 'avit.zsh-theme' and edit it. It's located in the themes/ directory in the oh-my-zsh distribution.
Find and delete '%{$(echotc UP 1)%}' and '%{$(echotc DO 1)%}' @line9, then write, quit, reboot.
It works fine on my end.

**Comment by pat-s** [comment]
Hey guys, just a quick question: Are zsh themes supported? Mine (agnoster) is not showing up.
