### ISSUE TITLE
Use winpty to support Windows

### ISSUE THREAD

**Issue by deathaxe** [Wramberg/TerminalView#83]
Microsoft VS Code uses https://github.com/rprichard/winpty as middleware to access PowerShell on Windows. Winpty is a package which provides an unix like API for PowerShell.

I am wondering whether it was possible to let TerminalView make use of it to make it work on Windows operating systems.

**Comment by rwols** [comment]
While I'm not a windows user, I'm very interested in this approach nonetheless.

**Comment by randy3k** [comment]
https://github.com/spyder-ide/pywinpty

There is also a python bindings to winpty

**Comment by urmilparikh** [comment]
Please add Windows support...

**Comment by urmilparikh** [comment]
Also consider cmder or git for windows options. They offer very usable bash shell.

**Comment by randy3k** [comment]
For the reference, I am working on a cross-platform Terminal
https://github.com/randy3k/Console

**Comment by urmilparikh** [comment]
@randy3k, Console works like a charm on Windows. Please give option to select default shell. I generally use cmder or Git for Windows (bash).

Thanks!

**Comment by randy3k** [comment]
@urmilparikh thank you for testing it. Please note that `cmder` is not a shell, it is a program which could open a number of shells, cmd, powershell or bash. Changing default shell is supported yet, but you could call the command `console_open` with the argument `cmd`.

**Comment by joelhandwell** [comment]
Microsoft is making [official API to create a third-party console host](https://github.com/Microsoft/console/issues/57) right now.

According to @DarthSpock's [comment](https://github.com/Microsoft/WSL/issues/1117#issuecomment-404828297) following:   
> Insider build 17711 and just awaiting a few critical bug fixes before ready for public consumption.

So you will soon have choice to use winpty or the offcial api to implement this.

**Comment by deathaxe** [comment]
This issue is fixed by https://packagecontrol.io/packages/Terminus which makes this package obsolete at least for me.
