### ISSUE TITLE
Red borders between lines

### ISSUE THREAD

**Issue by brownieboy** [Wramberg/TerminalView#85]
Just installed TerminalView for the first time.  When I open it, TerminalView defaults to displaying an ugly red border around all lines, like so:

<img width="446" alt="sublime-terminal" src="https://user-images.githubusercontent.com/1781909/37746582-0d77dd02-2dcf-11e8-8784-029344c83983.png">

This happens on two different machines: one Mac OS X Sierra (bash version 3.2.57(1)) and the other Xubuntu Linux (not sure of bash version there).  The two Sublime installs do have similar setups (plugins etc) otherwise though.

I suspected an incompatibility with either the Theme or Colour Scheme that I was using in Sublime.  I've tried changing both of those to other settings though, and I still get the red lines in TerminalView, even after restarting Sublime.

**Comment by rwols** [comment]
Do you have a plug-in called “trailing spaces”? See: https://github.com/Wramberg/TerminalView/issues/18

**Comment by brownieboy** [comment]
Bingo!  Yes, I do, indeed, have the TrailingSpaces plugin installed, and disabling it has solved the problem for me.

Many thanks, @rwols.

(Perhaps if the original reporter of #18 had spelled "borders" correctly, then I might have found that in the search before posting myself!)

Closing this issue.
