### ISSUE TITLE
Changing background color doesn't change background of non-white characters

### ISSUE THREAD

**Issue by dunderX** [Wramberg/TerminalView#86]
I tried to change the background color from black to #3f3f3f. So I changed all (4) occurrences of #000000 to #3f3f3f, but got this:

![screenshot-1](https://user-images.githubusercontent.com/28021979/38851791-eb154546-421f-11e8-824e-deb7535e50e5.png)

how can I eliminate the black behind the non-white characters?

Thanks for the awesome plugin!

**Comment by dunderX** [comment]
Thank you fore replying!
I did this change, and got this funny look:

![screenshot-2](https://user-images.githubusercontent.com/28021979/38922514-03c5d24a-4301-11e8-8d0e-62872c978a4c.png)

The username font color should be green and pwd should be blue, like in the first post. But the change ruind it somehow.

**Comment by Wramberg** [comment]
Sublime text has some weird bug that does not allow anything with a foreground color to have the same background. You have to change your background slightly there places where the color was `#000001`

**Comment by dunderX** [comment]
That's it!
thanks
