### ISSUE TITLE
Can't scroll in VIM mode

### ISSUE THREAD

**Issue by duraki** [Wramberg/TerminalView#91]
* OS used: Mac OSX 10.13.4
* Bash version: 3.2 (zsh: 5.3)
* Arguments being used with the terminal_view_open command: (none)
  
If you install or use [Vintageous](https://github.com/guillermooo/Vintageous) you can see that scrolling is not possible. I tried several things (page up/down, arrows, using Xj/k, gg and it all seems like history is not existent aka cursor/caret just starts on first line of visible TerminalView window.

**Comment by Wramberg** [comment]
Im not familiar with VIM mode but my best guess would be that the scrolling hotkeys are blocked by the VIM mode ? Have you tried specifically setting the TerminalView scroll hotkeys in your user keymap ?

**Comment by duraki** [comment]
Thanks for responding. Switched scrolling to `ctrl+j/k" and now it works. Shame I can't use modus like `10ctrl+j` tho.
