### ISSUE TITLE
Disappearing content (not scrollable)

### ISSUE THREAD

**Issue by Arcanius** [Wramberg/TerminalView#92]
When I run terminal in Sublime Text 3, it is unscrollable. Which means that when things get printed into the terminal, they get appended only as long as there is space on the page (height of the editor's window). When there's no more space, the content in the Terminal seemingly scrolls up and the new line gets appended, however, the oldest line from the top gets forever removed.

Unlike in normal text editor, where I can scroll up and down, in TerminalView it's gone (forever). If I resize the editor window, all history that doesn't fit into the new (smaller) window get's immediately and forever removed too.

**Comment by justinsutw** [comment]
You are referring to scrolling with mouse wheel, right?
Try using alt key with mouse wheel to scroll.

**Comment by Arcanius** [comment]
Nope, all I can do is Fn+Shift+Up/Down to scroll (as I recently found out). Would it be possible to allow scrolling the same way as in any other file?

I should probably note I'm on macOS.

**Comment by duraki** [comment]
Had same issue, maybe related to #91?

**Comment by Arcanius** [comment]
Yeah, I've seen it but I don't think it's related. I'm not using Vintageous and I don't need to bind hotkeys to anything because Fn+Shift+Up/Down can be used for scrolling. I would appreciate it if I could scroll with mouse instead of keys.

**Comment by duraki** [comment]
As far as I know, mouse scroll is working only on Linux. If you are on Macbook/MacOS, that is not quite possible since we are waiting for SublimeTextIssues/Core/issues/1838 fix. #28 for more on this.

**Comment by Arcanius** [comment]
Oh, I see. You're correct. Since it's been a year we probably aren't going to see any change anytime soon.

Thank you.

**Comment by duraki** [comment]
Indeed, you could ping core issue and close this one. It may help, hopefully. Cheers.
